In [15]:
import pandas as pd # For creating Data frames and reading files
import numpy as np # for any numerical analysis
import matplotlib.pyplot as plt
import seaborn as sns
import warnings; warnings.simplefilter("ignore")
file = pd.ExcelFile("/media/roshan/Data/Data Science case study/clasroomdatast (2).xls") #Read Excel files
file.sheet_names #To provide particular sheet name 
df1=file.parse('ClassPerformance') #Reading the file
df1

,Outcome,iqclass,name,Gender,age,Self_Rating,Teacher_Rating,Income,Section
0,1,1,JODIEAS,female,19.0000,0,0,211.3375,S
1,1,1,WHFLCMM,male,9.0833,1,2,151.5500,S
2,0,1,SAEBGBW,female,8.0000,1,2,151.5500,S
3,0,1,ATXRALL,male,20.0000,1,2,151.5500,S
4,0,1,EECLXJQ,female,15.0000,1,2,151.5500,S
5,1,1,TJEXCTB,male,19.0000,0,0,26.5500,S
6,1,1,JOLPKSD,female,15.0000,1,0,77.9583,S
7,0,1,NHPDPHO,male,16.0000,0,0,0.0000,S
8,1,1,XNBXOUM,female,17.0000,2,0,51.4792,S
9,0,1,UWXGVAI,male,17.0000,0,0,49.5042,C
10,0,1,OYNUGXV,male,18.0000,1,0,227.5250,C
11,1,1,WNBHHYC,female,8.0000,1,0,227.5250,C
12,1,1,TOJLDAK,female,14.0000,0,0,69.3000,C
13,1,1,DWNEVIS,female,16.0000,0,0,78.8500,S
14,1,1,PFBBSKO,male,15.0000,0,0,30.0000,S
15,0,1,ELEJIPC,male,NaN,0,0,25.9250,S
16,0,1,IGRQTMR,male,14.0000,0,1,247.5208,C
17,1,1,XDTKAJA,female,17.0000,0,1,247.5208,C
18,1,1,DQBJBHP,female,20.0000,0,0,76.2917,C
19,0,1,LGUMJSY,male,19.0000,0,0,75.2417,C
20,1,1,MJTSHAT,male,15.0000,1,1,52.5542,S
21,1,1,AGKROAN,female,16.0000,1,1,52.5542,S
22,1,1,OJCEJJK,male,16.0000,0,0,30.0000,C
23,1,1,MVRCBBY,female,17.0000,0,0,227.5250,C
24,1,1,CNXKSBV,female,19.0000,0,0,221.7792,S
25,0,1,WKEJNEY,male,15.0000,0,0,26.0000,C
26,1,1,QQMQBGR,male,15.0000,1,0,91.0792,C
27,1,1,FBLVLAH,female,9.0000,1,0,91.0792,C
28,1,1,ORWDROH,female,16.0000,0,0,135.6333,S
29,1,1,RFAANPA,male,18.0000,0,0,26.5500,S
...,...,...,...,...,...,...,...,...,...
1279,0,3,VWPRLXK,female,4.0000,0,0,7.8542,S
1280,0,3,HECSQJG,male,12.0000,0,0,7.8958,S
1281,0,3,EPJSYTH,male,12.0000,0,0,9.0000,S
1282,0,3,AOXIJNH,male,NaN,0,0,8.0500,S
1283,0,3,MLPIFSO,male,NaN,0,0,7.5500,S
1284,0,3,BNYHVRX,male,NaN,0,0,8.0500,S
1285,0,3,ATLOOID,male,18.0000,0,0,9.5000,S
1286,1,3,HCIWASS,female,17.0000,0,0,7.2292,C
1287,0,3,KHDXOHU,male,16.0000,0,0,7.7500,S
1288,0,3,DXNVFLJ,male,8.0000,1,0,6.4958,S
1289,0,3,ABHHPCH,male,11.0000,1,0,6.4958,S
1290,1,3,JWQFYJH,female,20.0000,1,0,7.0000,S
1291,0,3,TGMNBMM,male,NaN,0,0,8.7125,S
1292,0,3,HBKHARF,male,NaN,0,0,7.5500,S
1293,0,3,WAYFOCY,male,NaN,0,0,8.0500,S
1294,0,3,HOUQFEL,male,18.5000,0,0,16.1000,S
1295,0,3,UYPXMJI,male,11.0000,0,0,7.2500,S
1296,0,3,NGJWFEU,male,17.0000,0,0,8.6625,S
1297,0,3,GTACVTX,male,NaN,0,0,7.2500,S
1298,0,3,RWRLXEJ,male,16.0000,0,0,9.5000,S
1299,0,3,IAGCUOC,male,17.0000,1,0,14.4542,C
1300,1,3,QTHXGGA,female,5.0000,1,0,14.4542,C
1301,0,3,YPFXKNP,male,15.0000,0,0,7.2250,C
1302,0,3,KVPMVMX,male,NaN,0,0,7.2250,C
1303,0,3,RPVUBLP,male,NaN,0,0,14.4583,C
1304,0,3,QAPLCIH,female,4.5000,1,0,14.4542,C
1305,0,3,GDEDOKH,female,NaN,1,0,14.4542,C
1306,0,3,AETMPIU,male,16.5000,0,0,7.2250,C
1307,0,3,QJJVUBE,male,17.0000,0,0,7.2250,C
1308,0,3,MBOFYRG,male,19.0000,0,0,7.8750,S

In [16]:
df1.dtypes

Outcome             int64
iqclass             int64
name               object
Gender             object
age               float64
Self_Rating         int64
Teacher_Rating      int64
Income            float64
Section            object
dtype: object

In [17]:
df2=df1[["name","Outcome"]]
df2

         name  Outcome
0     JODIEAS        1
1     WHFLCMM        1
2     SAEBGBW        0
3     ATXRALL        0
4     EECLXJQ        0
5     TJEXCTB        1
6     JOLPKSD        1
7     NHPDPHO        0
8     XNBXOUM        1
9     UWXGVAI        0
10    OYNUGXV        0
11    WNBHHYC        1
12    TOJLDAK        1
13    DWNEVIS        1
14    PFBBSKO        1
15    ELEJIPC        0
16    IGRQTMR        0
17    XDTKAJA        1
18    DQBJBHP        1
19    LGUMJSY        0
20    MJTSHAT        1
21    AGKROAN        1
22    OJCEJJK        1
23    MVRCBBY        1
24    CNXKSBV        1
25    WKEJNEY        0
26    QQMQBGR        1
27    FBLVLAH        1
28    ORWDROH        1
29    RFAANPA        1
...       ...      ...
1279  VWPRLXK        0
1280  HECSQJG        0
1281  EPJSYTH        0
1282  AOXIJNH        0
1283  MLPIFSO        0
1284  BNYHVRX        0
1285  ATLOOID        0
1286  HCIWASS        1
1287  KHDXOHU        0
1288  DXNVFLJ        0
1289  ABHHPCH        0
1290  JWQFYJH        1
1291  TGMNBMM        0
1292  HBKHARF        0
1293  WAYFOCY        0
1294  HOUQFEL        0
1295  UYPXMJI        0
1296  NGJWFEU        0
1297  GTACVTX        0
1298  RWRLXEJ        0
1299  IAGCUOC        0
1300  QTHXGGA        1
1301  YPFXKNP        0
1302  KVPMVMX        0
1303  RPVUBLP        0
1304  QAPLCIH        0
1305  GDEDOKH        0
1306  AETMPIU        0
1307  QJJVUBE        0
1308  MBOFYRG        0

[1309 rows x 2 columns]

In [18]:
PassedStudents=df2.loc[df2["Outcome"]==1]
PassedStudents

         name  Outcome
0     JODIEAS        1
1     WHFLCMM        1
5     TJEXCTB        1
6     JOLPKSD        1
8     XNBXOUM        1
11    WNBHHYC        1
12    TOJLDAK        1
13    DWNEVIS        1
14    PFBBSKO        1
17    XDTKAJA        1
18    DQBJBHP        1
20    MJTSHAT        1
21    AGKROAN        1
22    OJCEJJK        1
23    MVRCBBY        1
24    CNXKSBV        1
26    QQMQBGR        1
27    FBLVLAH        1
28    ORWDROH        1
29    RFAANPA        1
31    GMIPAYA        1
32    SWUDPNB        1
33    GUVVPLP        1
35    WCUWNKP        1
36    TIHNITV        1
37    RQARRGV        1
41    MQBSPCX        1
42    GEBGAUJ        1
43    IJHCINT        1
44    PRTIPRY        1
...       ...      ...
1159  XMNUTCT        1
1162  BNVAGBM        1
1182  IANQPBB        1
1187  BCHJAXK        1
1188  ABOGIAL        1
1189  CGPQRBM        1
1190  RMQGKDR        1
1196  AGAERXY        1
1198  PKJQTDL        1
1205  RVUWDMM        1
1216  SXESSDO        1
1223  DXMNEMR        1
1228  FQBLLAN        1
1232  YKSDFNP        1
1233  GRRQODA        1
1236  KTPSXNR        1
1238  PLPSTDH        1
1240  RUCTRNY        1
1244  XDPKSTK        1
1247  OKAICIN        1
1254  ESUQLBM        1
1256  CVDPYME        1
1257  TVGRTGK        1
1258  FMPRLWV        1
1260  FGPFQOT        1
1261  WAMEILB        1
1277  IAWSTAE        1
1286  HCIWASS        1
1290  JWQFYJH        1
1300  QTHXGGA        1

[500 rows x 2 columns]

In [19]:
FailedStudents=df2.loc[df2["Outcome"]==0]
FailedStudents

         name  Outcome
2     SAEBGBW        0
3     ATXRALL        0
4     EECLXJQ        0
7     NHPDPHO        0
9     UWXGVAI        0
10    OYNUGXV        0
15    ELEJIPC        0
16    IGRQTMR        0
19    LGUMJSY        0
25    WKEJNEY        0
30    LIROOCD        0
34    MYHAVCY        0
38    GENUOAS        0
39    GVRFFWF        0
40    HBLWGXS        0
45    YXRHXJD        0
46    LLLBDAH        0
51    KOBXOJV        0
52    WSMNWVH        0
53    UKLOLMT        0
58    UWDKEKS        0
60    JJUJNNL        0
62    IERCYXG        0
70    RLXWETC        0
71    XLTNNOA        0
74    DWFEWKW        0
75    NNUUXXA        0
77    SBNLRMP        0
80    REKRAMN        0
81    NSQIQEA        0
...       ...      ...
1275  QVBJXDA        0
1276  ESPVPER        0
1278  GAGWBDX        0
1279  VWPRLXK        0
1280  HECSQJG        0
1281  EPJSYTH        0
1282  AOXIJNH        0
1283  MLPIFSO        0
1284  BNYHVRX        0
1285  ATLOOID        0
1287  KHDXOHU        0
1288  DXNVFLJ        0
1289  ABHHPCH        0
1291  TGMNBMM        0
1292  HBKHARF        0
1293  WAYFOCY        0
1294  HOUQFEL        0
1295  UYPXMJI        0
1296  NGJWFEU        0
1297  GTACVTX        0
1298  RWRLXEJ        0
1299  IAGCUOC        0
1301  YPFXKNP        0
1302  KVPMVMX        0
1303  RPVUBLP        0
1304  QAPLCIH        0
1305  GDEDOKH        0
1306  AETMPIU        0
1307  QJJVUBE        0
1308  MBOFYRG        0

[809 rows x 2 columns]

In [20]:
df3=df1[["name","iqclass"]]
df3

         name  iqclass
0     JODIEAS        1
1     WHFLCMM        1
2     SAEBGBW        1
3     ATXRALL        1
4     EECLXJQ        1
5     TJEXCTB        1
6     JOLPKSD        1
7     NHPDPHO        1
8     XNBXOUM        1
9     UWXGVAI        1
10    OYNUGXV        1
11    WNBHHYC        1
12    TOJLDAK        1
13    DWNEVIS        1
14    PFBBSKO        1
15    ELEJIPC        1
16    IGRQTMR        1
17    XDTKAJA        1
18    DQBJBHP        1
19    LGUMJSY        1
20    MJTSHAT        1
21    AGKROAN        1
22    OJCEJJK        1
23    MVRCBBY        1
24    CNXKSBV        1
25    WKEJNEY        1
26    QQMQBGR        1
27    FBLVLAH        1
28    ORWDROH        1
29    RFAANPA        1
...       ...      ...
1279  VWPRLXK        3
1280  HECSQJG        3
1281  EPJSYTH        3
1282  AOXIJNH        3
1283  MLPIFSO        3
1284  BNYHVRX        3
1285  ATLOOID        3
1286  HCIWASS        3
1287  KHDXOHU        3
1288  DXNVFLJ        3
1289  ABHHPCH        3
1290  JWQFYJH        3
1291  TGMNBMM        3
1292  HBKHARF        3
1293  WAYFOCY        3
1294  HOUQFEL        3
1295  UYPXMJI        3
1296  NGJWFEU        3
1297  GTACVTX        3
1298  RWRLXEJ        3
1299  IAGCUOC        3
1300  QTHXGGA        3
1301  YPFXKNP        3
1302  KVPMVMX        3
1303  RPVUBLP        3
1304  QAPLCIH        3
1305  GDEDOKH        3
1306  AETMPIU        3
1307  QJJVUBE        3
1308  MBOFYRG        3

[1309 rows x 2 columns]

In [21]:
HighIQstudents=df3.loc[df3["iqclass"]==3]
HighIQstudents

         name  iqclass
600   NMFMJNB        3
601   QQDTGQB        3
602   RCEFHAO        3
603   OXJCTAX        3
604   CSTCBKY        3
605   XAUBRRR        3
606   VPNLQVA        3
607   DBHXIOG        3
608   BMQUJIN        3
609   OJRMUTL        3
610   IFMPSCR        3
611   KMNOOLB        3
612   XUJUDBQ        3
613   HUJPYDU        3
614   HMSQPBX        3
615   PSBPIKS        3
616   XLILLFO        3
617   KNBTDMQ        3
618   UKDKTIQ        3
619   KPLXRPJ        3
620   CIGNLNP        3
621   QJNPHDB        3
622   KKKRFXL        3
623   HLBXRIJ        3
624   RBPXUVP        3
625   BLEKGGD        3
626   OSTXQNF        3
627   GCYTDBP        3
628   JXVOYBL        3
629   VEXLTHC        3
...       ...      ...
1279  VWPRLXK        3
1280  HECSQJG        3
1281  EPJSYTH        3
1282  AOXIJNH        3
1283  MLPIFSO        3
1284  BNYHVRX        3
1285  ATLOOID        3
1286  HCIWASS        3
1287  KHDXOHU        3
1288  DXNVFLJ        3
1289  ABHHPCH        3
1290  JWQFYJH        3
1291  TGMNBMM        3
1292  HBKHARF        3
1293  WAYFOCY        3
1294  HOUQFEL        3
1295  UYPXMJI        3
1296  NGJWFEU        3
1297  GTACVTX        3
1298  RWRLXEJ        3
1299  IAGCUOC        3
1300  QTHXGGA        3
1301  YPFXKNP        3
1302  KVPMVMX        3
1303  RPVUBLP        3
1304  QAPLCIH        3
1305  GDEDOKH        3
1306  AETMPIU        3
1307  QJJVUBE        3
1308  MBOFYRG        3

[709 rows x 2 columns]

In [22]:
AverrageIQstudents=df3.loc[df3["iqclass"]==2]
AverrageIQstudents

        name  iqclass
323  LUEMTJD        2
324  IEFRAHL        2
325  VMVEGQX        2
326  EATNWWX        2
327  VQAWNGY        2
328  FABEYXH        2
329  TLWMPCM        2
330  DLKAJSI        2
331  ECOEMWE        2
332  LOBLMQD        2
333  PCYXXYB        2
334  POJGPVC        2
335  BJLVTAM        2
336  YDCFFFW        2
337  CTIRAVV        2
338  XFLRKTR        2
339  DNFCDGA        2
340  VQFTNYH        2
341  WIDDXOW        2
342  LIDJYSH        2
343  IVBULOT        2
344  OCYXJQY        2
345  VEGUFQF        2
346  BURCMIB        2
347  AVJXCRA        2
348  OTPOJCF        2
349  OKXULDS        2
350  HSHATBP        2
351  GUDDEHG        2
352  JYIVEJW        2
..       ...      ...
570  XALNQBT        2
571  EDYEGPB        2
572  PWGJEIH        2
573  LMUUXNN        2
574  VUGOSYD        2
575  CVTQGIK        2
576  KLALUUV        2
577  JLYIPYN        2
578  JDTKJJC        2
579  HOTAQVP        2
580  XIIDIMA        2
581  BFATQPY        2
582  PEBIRSL        2
583  AQQRNEY        2
584  LMAVQXR        2
585  VHSSXPI        2
586  XVJKFFJ        2
587  BYYKEFE        2
588  TXQFYYC        2
589  ATJNPHE        2
590  UBLDGYT        2
591  KBDBOIP        2
592  HRYIEXJ        2
593  IHJQIPY        2
594  NJAMSVE        2
595  TBWYNTB        2
596  VQHDKIV        2
597  JVSYIDS        2
598  QYLQTSB        2
599  GDBBJOY        2

[277 rows x 2 columns]

In [23]:
LowIQstudents=df3.loc[df3["iqclass"]==1]
LowIQstudents

        name  iqclass
0    JODIEAS        1
1    WHFLCMM        1
2    SAEBGBW        1
3    ATXRALL        1
4    EECLXJQ        1
5    TJEXCTB        1
6    JOLPKSD        1
7    NHPDPHO        1
8    XNBXOUM        1
9    UWXGVAI        1
10   OYNUGXV        1
11   WNBHHYC        1
12   TOJLDAK        1
13   DWNEVIS        1
14   PFBBSKO        1
15   ELEJIPC        1
16   IGRQTMR        1
17   XDTKAJA        1
18   DQBJBHP        1
19   LGUMJSY        1
20   MJTSHAT        1
21   AGKROAN        1
22   OJCEJJK        1
23   MVRCBBY        1
24   CNXKSBV        1
25   WKEJNEY        1
26   QQMQBGR        1
27   FBLVLAH        1
28   ORWDROH        1
29   RFAANPA        1
..       ...      ...
293  HFUQIOM        1
294  KSKWAGD        1
295  SNRGQNU        1
296  EIRUSOQ        1
297  KFJCANN        1
298  GTOPXSD        1
299  NHIINMP        1
300  XWOYFVB        1
301  OXTXNMN        1
302  YETGNUM        1
303  STPUDFK        1
304  OCWQHCI        1
305  LPKXHQM        1
306  GBVVGPE        1
307  XYANMNE        1
308  QKYSNUO        1
309  JACDLVX        1
310  JQTDNRU        1
311  QKDENYO        1
312  RFSMNCN        1
313  HCCCRWT        1
314  IFXJUWM        1
315  YASQXDF        1
316  YCMJCRH        1
317  KACXFGV        1
318  FJUDVYQ        1
319  TCRAWKR        1
320  NKUVBTW        1
321  GSLQKAJ        1
322  REEMINN        1

[323 rows x 2 columns]

In [24]:
df4=df1[["name","Self_Rating"]]
df4

         name  Self_Rating
0     JODIEAS            0
1     WHFLCMM            1
2     SAEBGBW            1
3     ATXRALL            1
4     EECLXJQ            1
5     TJEXCTB            0
6     JOLPKSD            1
7     NHPDPHO            0
8     XNBXOUM            2
9     UWXGVAI            0
10    OYNUGXV            1
11    WNBHHYC            1
12    TOJLDAK            0
13    DWNEVIS            0
14    PFBBSKO            0
15    ELEJIPC            0
16    IGRQTMR            0
17    XDTKAJA            0
18    DQBJBHP            0
19    LGUMJSY            0
20    MJTSHAT            1
21    AGKROAN            1
22    OJCEJJK            0
23    MVRCBBY            0
24    CNXKSBV            0
25    WKEJNEY            0
26    QQMQBGR            1
27    FBLVLAH            1
28    ORWDROH            0
29    RFAANPA            0
...       ...          ...
1279  VWPRLXK            0
1280  HECSQJG            0
1281  EPJSYTH            0
1282  AOXIJNH            0
1283  MLPIFSO            0
1284  BNYHVRX            0
1285  ATLOOID            0
1286  HCIWASS            0
1287  KHDXOHU            0
1288  DXNVFLJ            1
1289  ABHHPCH            1
1290  JWQFYJH            1
1291  TGMNBMM            0
1292  HBKHARF            0
1293  WAYFOCY            0
1294  HOUQFEL            0
1295  UYPXMJI            0
1296  NGJWFEU            0
1297  GTACVTX            0
1298  RWRLXEJ            0
1299  IAGCUOC            1
1300  QTHXGGA            1
1301  YPFXKNP            0
1302  KVPMVMX            0
1303  RPVUBLP            0
1304  QAPLCIH            1
1305  GDEDOKH            1
1306  AETMPIU            0
1307  QJJVUBE            0
1308  MBOFYRG            0

[1309 rows x 2 columns]

In [25]:
HigherSelfRating=df4.loc[df4["Self_Rating"]==2]
HigherSelfRating

         name  Self_Rating
8     XNBXOUM            2
42    GEBGAUJ            2
79    FNXSUOS            2
119   OFCOHYV            2
206   CTMWGBH            2
249   XMLFBLN            2
250   IMGWEIY            2
251   JQOAMGB            2
339   DNFCDGA            2
340   VQFTNYH            2
341   WIDDXOW            2
442   OYQFPWV            2
443   CIBFCST            2
444   VUMGBUJ            2
446   ANAQNCD            2
447   HARJDKV            2
460   UJMBQPF            2
462   VFGCDHS            2
463   GFBDJSU            2
550   QGOAVXU            2
657   XNSVTDL            2
658   XHSSLJC            2
659   KGRNWHI            2
752   UGJOWNE            2
754   YYFWPXC            2
755   LTIHIBQ            2
806   DNVJSXU            2
807   PCVYWMJ            2
809   DPHRFTM            2
837   BAKWBBE            2
838   CCDYNMU            2
848   VGUVOPT            2
932   RPGJOLA            2
933   AWRCHYG            2
1001  GNCBMOK            2
1002  RSMMBSJ            2
1003  YVVDMLJ            2
1184  NBCGEFF            2
1185  HCJOVUU            2
1186  HVCNLGP            2
1273  YBMOALF            2
1275  QVBJXDA            2

In [26]:
LowerSelfRating=df4.loc[df4["Self_Rating"]==0]
LowerSelfRating

         name  Self_Rating
0     JODIEAS            0
5     TJEXCTB            0
7     NHPDPHO            0
9     UWXGVAI            0
12    TOJLDAK            0
13    DWNEVIS            0
14    PFBBSKO            0
15    ELEJIPC            0
16    IGRQTMR            0
17    XDTKAJA            0
18    DQBJBHP            0
19    LGUMJSY            0
22    OJCEJJK            0
23    MVRCBBY            0
24    CNXKSBV            0
25    WKEJNEY            0
28    ORWDROH            0
29    RFAANPA            0
30    LIROOCD            0
31    GMIPAYA            0
32    SWUDPNB            0
33    GUVVPLP            0
34    MYHAVCY            0
35    WCUWNKP            0
36    TIHNITV            0
37    RQARRGV            0
38    GENUOAS            0
39    GVRFFWF            0
40    HBLWGXS            0
41    MQBSPCX            0
...       ...          ...
1268  GEQSRLI            0
1269  ASWHMKJ            0
1270  UUKSEPM            0
1271  LXEVONC            0
1272  BIOKPJI            0
1277  IAWSTAE            0
1278  GAGWBDX            0
1279  VWPRLXK            0
1280  HECSQJG            0
1281  EPJSYTH            0
1282  AOXIJNH            0
1283  MLPIFSO            0
1284  BNYHVRX            0
1285  ATLOOID            0
1286  HCIWASS            0
1287  KHDXOHU            0
1291  TGMNBMM            0
1292  HBKHARF            0
1293  WAYFOCY            0
1294  HOUQFEL            0
1295  UYPXMJI            0
1296  NGJWFEU            0
1297  GTACVTX            0
1298  RWRLXEJ            0
1301  YPFXKNP            0
1302  KVPMVMX            0
1303  RPVUBLP            0
1306  AETMPIU            0
1307  QJJVUBE            0
1308  MBOFYRG            0

[891 rows x 2 columns]

In [27]:
df5=df1[["name","Teacher_Rating"]]
df5

         name  Teacher_Rating
0     JODIEAS               0
1     WHFLCMM               2
2     SAEBGBW               2
3     ATXRALL               2
4     EECLXJQ               2
5     TJEXCTB               0
6     JOLPKSD               0
7     NHPDPHO               0
8     XNBXOUM               0
9     UWXGVAI               0
10    OYNUGXV               0
11    WNBHHYC               0
12    TOJLDAK               0
13    DWNEVIS               0
14    PFBBSKO               0
15    ELEJIPC               0
16    IGRQTMR               1
17    XDTKAJA               1
18    DQBJBHP               0
19    LGUMJSY               0
20    MJTSHAT               1
21    AGKROAN               1
22    OJCEJJK               0
23    MVRCBBY               0
24    CNXKSBV               0
25    WKEJNEY               0
26    QQMQBGR               0
27    FBLVLAH               0
28    ORWDROH               0
29    RFAANPA               0
...       ...             ...
1279  VWPRLXK               0
1280  HECSQJG               0
1281  EPJSYTH               0
1282  AOXIJNH               0
1283  MLPIFSO               0
1284  BNYHVRX               0
1285  ATLOOID               0
1286  HCIWASS               0
1287  KHDXOHU               0
1288  DXNVFLJ               0
1289  ABHHPCH               0
1290  JWQFYJH               0
1291  TGMNBMM               0
1292  HBKHARF               0
1293  WAYFOCY               0
1294  HOUQFEL               0
1295  UYPXMJI               0
1296  NGJWFEU               0
1297  GTACVTX               0
1298  RWRLXEJ               0
1299  IAGCUOC               0
1300  QTHXGGA               0
1301  YPFXKNP               0
1302  KVPMVMX               0
1303  RPVUBLP               0
1304  QAPLCIH               0
1305  GDEDOKH               0
1306  AETMPIU               0
1307  QJJVUBE               0
1308  MBOFYRG               0

[1309 rows x 2 columns]

In [28]:
TeacherRatedHigh=df5.loc[df5["Teacher_Rating"]==2]
TeacherRatedHigh

         name  Teacher_Rating
1     WHFLCMM               2
2     SAEBGBW               2
3     ATXRALL               2
4     EECLXJQ               2
54    LJIHYUJ               2
55    LIOXGEM               2
56    KKLBUCI               2
57    DNROPHH               2
78    CUJYOAG               2
82    MMYTACC               2
90    HODUBDQ               2
94    BEIMLWV               2
111   GWLERNL               2
112   NTWEAIW               2
113   FPRSGEP               2
114   EOYAXWN               2
122   OFNENHE               2
215   BUVRYHE               2
216   FQKEVUL               2
249   XMLFBLN               2
250   IMGWEIY               2
251   JQOAMGB               2
273   UWBDKAO               2
289   XVJTNUM               2
295   SNRGQNU               2
309   JACDLVX               2
313   HCCCRWT               2
350   HSHATBP               2
359   NUCCPSS               2
371   DHSOFBD               2
...       ...             ...
830   WGTYCPV               2
899   FAMCCLU               2
900   OCOXAQJ               2
901   EXFSHJI               2
902   HHRFWNU               2
903   JAVGDWA               2
934   QXFADYB               2
939   LCXVTSD               2
1036  UOGQRPW               2
1048  VSWOQPP               2
1113  HPXPGOY               2
1123  BQITVBD               2
1158  DRGFKWR               2
1170  KLDXXBI               2
1171  VECKQRF               2
1172  UGISYJM               2
1173  XWBIRPH               2
1174  VBSLDPF               2
1175  EUNBROW               2
1176  XTPLWLN               2
1177  INKJXSW               2
1178  KTNOXTB               2
1188  ABOGIAL               2
1206  NETGRHL               2
1207  IEBYQJP               2
1208  YKLATTE               2
1209  NXKYJOK               2
1258  FMPRLWV               2
1264  CSVFUXQ               2
1265  OEXYLCT               2

[113 rows x 2 columns]

In [29]:
TeacherRatedLow=df5.loc[df5["Teacher_Rating"]==0]
TeacherRatedLow

         name  Teacher_Rating
0     JODIEAS               0
5     TJEXCTB               0
6     JOLPKSD               0
7     NHPDPHO               0
8     XNBXOUM               0
9     UWXGVAI               0
10    OYNUGXV               0
11    WNBHHYC               0
12    TOJLDAK               0
13    DWNEVIS               0
14    PFBBSKO               0
15    ELEJIPC               0
18    DQBJBHP               0
19    LGUMJSY               0
22    OJCEJJK               0
23    MVRCBBY               0
24    CNXKSBV               0
25    WKEJNEY               0
26    QQMQBGR               0
27    FBLVLAH               0
28    ORWDROH               0
29    RFAANPA               0
30    LIROOCD               0
31    GMIPAYA               0
32    SWUDPNB               0
33    GUVVPLP               0
34    MYHAVCY               0
35    WCUWNKP               0
37    RQARRGV               0
38    GENUOAS               0
...       ...             ...
1279  VWPRLXK               0
1280  HECSQJG               0
1281  EPJSYTH               0
1282  AOXIJNH               0
1283  MLPIFSO               0
1284  BNYHVRX               0
1285  ATLOOID               0
1286  HCIWASS               0
1287  KHDXOHU               0
1288  DXNVFLJ               0
1289  ABHHPCH               0
1290  JWQFYJH               0
1291  TGMNBMM               0
1292  HBKHARF               0
1293  WAYFOCY               0
1294  HOUQFEL               0
1295  UYPXMJI               0
1296  NGJWFEU               0
1297  GTACVTX               0
1298  RWRLXEJ               0
1299  IAGCUOC               0
1300  QTHXGGA               0
1301  YPFXKNP               0
1302  KVPMVMX               0
1303  RPVUBLP               0
1304  QAPLCIH               0
1305  GDEDOKH               0
1306  AETMPIU               0
1307  QJJVUBE               0
1308  MBOFYRG               0

[1002 rows x 2 columns]

In [30]:
df6=df1[["name","Income"]]
df6

         name    Income
0     JODIEAS  211.3375
1     WHFLCMM  151.5500
2     SAEBGBW  151.5500
3     ATXRALL  151.5500
4     EECLXJQ  151.5500
5     TJEXCTB   26.5500
6     JOLPKSD   77.9583
7     NHPDPHO    0.0000
8     XNBXOUM   51.4792
9     UWXGVAI   49.5042
10    OYNUGXV  227.5250
11    WNBHHYC  227.5250
12    TOJLDAK   69.3000
13    DWNEVIS   78.8500
14    PFBBSKO   30.0000
15    ELEJIPC   25.9250
16    IGRQTMR  247.5208
17    XDTKAJA  247.5208
18    DQBJBHP   76.2917
19    LGUMJSY   75.2417
20    MJTSHAT   52.5542
21    AGKROAN   52.5542
22    OJCEJJK   30.0000
23    MVRCBBY  227.5250
24    CNXKSBV  221.7792
25    WKEJNEY   26.0000
26    QQMQBGR   91.0792
27    FBLVLAH   91.0792
28    ORWDROH  135.6333
29    RFAANPA   26.5500
...       ...       ...
1279  VWPRLXK    7.8542
1280  HECSQJG    7.8958
1281  EPJSYTH    9.0000
1282  AOXIJNH    8.0500
1283  MLPIFSO    7.5500
1284  BNYHVRX    8.0500
1285  ATLOOID    9.5000
1286  HCIWASS    7.2292
1287  KHDXOHU    7.7500
1288  DXNVFLJ    6.4958
1289  ABHHPCH    6.4958
1290  JWQFYJH    7.0000
1291  TGMNBMM    8.7125
1292  HBKHARF    7.5500
1293  WAYFOCY    8.0500
1294  HOUQFEL   16.1000
1295  UYPXMJI    7.2500
1296  NGJWFEU    8.6625
1297  GTACVTX    7.2500
1298  RWRLXEJ    9.5000
1299  IAGCUOC   14.4542
1300  QTHXGGA   14.4542
1301  YPFXKNP    7.2250
1302  KVPMVMX    7.2250
1303  RPVUBLP   14.4583
1304  QAPLCIH   14.4542
1305  GDEDOKH   14.4542
1306  AETMPIU    7.2250
1307  QJJVUBE    7.2250
1308  MBOFYRG    7.8750

[1309 rows x 2 columns]

In [31]:
df7=df1[["name","Section"]]
df7

         name Section
0     JODIEAS       S
1     WHFLCMM       S
2     SAEBGBW       S
3     ATXRALL       S
4     EECLXJQ       S
5     TJEXCTB       S
6     JOLPKSD       S
7     NHPDPHO       S
8     XNBXOUM       S
9     UWXGVAI       C
10    OYNUGXV       C
11    WNBHHYC       C
12    TOJLDAK       C
13    DWNEVIS       S
14    PFBBSKO       S
15    ELEJIPC       S
16    IGRQTMR       C
17    XDTKAJA       C
18    DQBJBHP       C
19    LGUMJSY       C
20    MJTSHAT       S
21    AGKROAN       S
22    OJCEJJK       C
23    MVRCBBY       C
24    CNXKSBV       S
25    WKEJNEY       C
26    QQMQBGR       C
27    FBLVLAH       C
28    ORWDROH       S
29    RFAANPA       S
...       ...     ...
1279  VWPRLXK       S
1280  HECSQJG       S
1281  EPJSYTH       S
1282  AOXIJNH       S
1283  MLPIFSO       S
1284  BNYHVRX       S
1285  ATLOOID       S
1286  HCIWASS       C
1287  KHDXOHU       S
1288  DXNVFLJ       S
1289  ABHHPCH       S
1290  JWQFYJH       S
1291  TGMNBMM       S
1292  HBKHARF       S
1293  WAYFOCY       S
1294  HOUQFEL       S
1295  UYPXMJI       S
1296  NGJWFEU       S
1297  GTACVTX       S
1298  RWRLXEJ       S
1299  IAGCUOC       C
1300  QTHXGGA       C
1301  YPFXKNP       C
1302  KVPMVMX       C
1303  RPVUBLP       C
1304  QAPLCIH       C
1305  GDEDOKH       C
1306  AETMPIU       C
1307  QJJVUBE       C
1308  MBOFYRG       S

[1309 rows x 2 columns]

In [32]:
GoodInReasoning=df7.loc[df7["Section"]=="S"]
GoodInReasoning

         name Section
0     JODIEAS       S
1     WHFLCMM       S
2     SAEBGBW       S
3     ATXRALL       S
4     EECLXJQ       S
5     TJEXCTB       S
6     JOLPKSD       S
7     NHPDPHO       S
8     XNBXOUM       S
13    DWNEVIS       S
14    PFBBSKO       S
15    ELEJIPC       S
20    MJTSHAT       S
21    AGKROAN       S
24    CNXKSBV       S
28    ORWDROH       S
29    RFAANPA       S
30    LIROOCD       S
32    SWUDPNB       S
33    GUVVPLP       S
34    MYHAVCY       S
36    TIHNITV       S
37    RQARRGV       S
38    GENUOAS       S
42    GEBGAUJ       S
45    YXRHXJD       S
46    LLLBDAH       S
47    LFCPPRP       S
51    KOBXOJV       S
52    WSMNWVH       S
...       ...     ...
1268  GEQSRLI       S
1269  ASWHMKJ       S
1270  UUKSEPM       S
1271  LXEVONC       S
1272  BIOKPJI       S
1273  YBMOALF       S
1274  CLBHAID       S
1275  QVBJXDA       S
1276  ESPVPER       S
1278  GAGWBDX       S
1279  VWPRLXK       S
1280  HECSQJG       S
1281  EPJSYTH       S
1282  AOXIJNH       S
1283  MLPIFSO       S
1284  BNYHVRX       S
1285  ATLOOID       S
1287  KHDXOHU       S
1288  DXNVFLJ       S
1289  ABHHPCH       S
1290  JWQFYJH       S
1291  TGMNBMM       S
1292  HBKHARF       S
1293  WAYFOCY       S
1294  HOUQFEL       S
1295  UYPXMJI       S
1296  NGJWFEU       S
1297  GTACVTX       S
1298  RWRLXEJ       S
1308  MBOFYRG       S

[915 rows x 2 columns]

In [33]:
GoodInVerbal=df7.loc[df7["Section"]=="C"]
GoodInVerbal

         name Section
9     UWXGVAI       C
10    OYNUGXV       C
11    WNBHHYC       C
12    TOJLDAK       C
16    IGRQTMR       C
17    XDTKAJA       C
18    DQBJBHP       C
19    LGUMJSY       C
22    OJCEJJK       C
23    MVRCBBY       C
25    WKEJNEY       C
26    QQMQBGR       C
27    FBLVLAH       C
31    GMIPAYA       C
35    WCUWNKP       C
39    GVRFFWF       C
40    HBLWGXS       C
41    MQBSPCX       C
43    IJHCINT       C
44    PRTIPRY       C
48    FNFRHIH       C
49    LJHLCHD       C
50    KVWNXLW       C
59    PYMPTYV       C
66    EAWBHSQ       C
68    IXRDTBY       C
71    XLTNNOA       C
72    LCREGSI       C
76    SWOQXUI       C
77    SBNLRMP       C
...       ...     ...
1137  RWSOLBY       C
1164  VWYSOUN       C
1165  ETBEHGE       C
1166  XHNMSTI       C
1184  NBCGEFF       C
1185  HCJOVUU       C
1186  HVCNLGP       C
1201  IYSUPBQ       C
1222  CEABCXV       C
1240  RUCTRNY       C
1241  KASMJCQ       C
1242  YPECDMH       C
1243  MCGJYQS       C
1244  XDPKSTK       C
1253  NGLCMIS       C
1255  LNOMYYQ       C
1256  CVDPYME       C
1257  TVGRTGK       C
1258  FMPRLWV       C
1277  IAWSTAE       C
1286  HCIWASS       C
1299  IAGCUOC       C
1300  QTHXGGA       C
1301  YPFXKNP       C
1302  KVPMVMX       C
1303  RPVUBLP       C
1304  QAPLCIH       C
1305  GDEDOKH       C
1306  AETMPIU       C
1307  QJJVUBE       C

[270 rows x 2 columns]

In [34]:
GoodInDataInterpretation=df7.loc[df7["Section"]=="Q"]
GoodInDataInterpretation

         name Section
206   CTMWGBH       Q
207   AFMQULX       Q
208   YGDXXWI       Q
284   QTXOGSY       Q
469   CSNDYTY       Q
470   OPHKRIG       Q
472   OTHHNPM       Q
477   RWFLIEO       Q
487   TTATNVA       Q
511   VEBQOPT       Q
562   YFIQDRA       Q
667   YKCOKMS       Q
682   FRIXYVT       Q
683   BSGVLHX       Q
684   NGJRHWC       Q
686   WFLWKRK       Q
692   SDCEKLN       Q
693   DEGGGLU       Q
694   GONBKSE       Q
695   NTXIOIQ       Q
702   CBXLYQL       Q
703   LGDJVWG       Q
709   QIVTOCR       Q
710   NHGAIVS       Q
713   RFJSRIY       Q
720   QDGKEUE       Q
723   VQJYWKG       Q
724   CBKBPOV       Q
725   AUVBCLE       Q
726   MIFXASM       Q
...       ...     ...
1054  ELUKIUC       Q
1069  WTDSPEO       Q
1070  SBNVCMK       Q
1071  QEASPVH       Q
1072  PIIWHSL       Q
1073  VRUVJAQ       Q
1074  JJNAQOJ       Q
1076  UKLTYMU       Q
1077  QMWBXOG       Q
1078  NTNPBCN       Q
1080  LMIYXFN       Q
1081  XXRXBQE       Q
1095  HGQNGSU       Q
1124  CMBLBTF       Q
1141  MYKSVOH       Q
1142  NOKSEYD       Q
1143  MWASHUM       Q
1144  KSTLHNY       Q
1145  MJLUSCL       Q
1146  YYGCRLW       Q
1149  TWPFELN       Q
1162  BNVAGBM       Q
1163  OBDKYTO       Q
1167  DLRAVYO       Q
1193  QYRMHAT       Q
1195  IKMWLJD       Q
1198  PKJQTDL       Q
1215  AACAHRU       Q
1216  SXESSDO       Q
1249  PDRICMJ       Q

[124 rows x 2 columns]

In [35]:
df8=df1[["name","age"]]
df8

         name      age
0     JODIEAS  19.0000
1     WHFLCMM   9.0833
2     SAEBGBW   8.0000
3     ATXRALL  20.0000
4     EECLXJQ  15.0000
5     TJEXCTB  19.0000
6     JOLPKSD  15.0000
7     NHPDPHO  16.0000
8     XNBXOUM  17.0000
9     UWXGVAI  17.0000
10    OYNUGXV  18.0000
11    WNBHHYC   8.0000
12    TOJLDAK  14.0000
13    DWNEVIS  16.0000
14    PFBBSKO  15.0000
15    ELEJIPC      NaN
16    IGRQTMR  14.0000
17    XDTKAJA  17.0000
18    DQBJBHP  20.0000
19    LGUMJSY  19.0000
20    MJTSHAT  15.0000
21    AGKROAN  16.0000
22    OJCEJJK  16.0000
23    MVRCBBY  17.0000
24    CNXKSBV  19.0000
25    WKEJNEY  15.0000
26    QQMQBGR  15.0000
27    FBLVLAH   9.0000
28    ORWDROH  16.0000
29    RFAANPA  18.0000
...       ...      ...
1279  VWPRLXK   4.0000
1280  HECSQJG  12.0000
1281  EPJSYTH  12.0000
1282  AOXIJNH      NaN
1283  MLPIFSO      NaN
1284  BNYHVRX      NaN
1285  ATLOOID  18.0000
1286  HCIWASS  17.0000
1287  KHDXOHU  16.0000
1288  DXNVFLJ   8.0000
1289  ABHHPCH  11.0000
1290  JWQFYJH  20.0000
1291  TGMNBMM      NaN
1292  HBKHARF      NaN
1293  WAYFOCY      NaN
1294  HOUQFEL  18.5000
1295  UYPXMJI  11.0000
1296  NGJWFEU  17.0000
1297  GTACVTX      NaN
1298  RWRLXEJ  16.0000
1299  IAGCUOC  17.0000
1300  QTHXGGA   5.0000
1301  YPFXKNP  15.0000
1302  KVPMVMX      NaN
1303  RPVUBLP      NaN
1304  QAPLCIH   4.5000
1305  GDEDOKH      NaN
1306  AETMPIU  16.5000
1307  QJJVUBE  17.0000
1308  MBOFYRG  19.0000

[1309 rows x 2 columns]